crm.chemtelinc.com/Models/CrestwoodLog.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace crm.chemtelinc.com.Models
{
    public class CrestwoodLog
    {
        //General Incident Fields
        public int id { get; set; }
        public string CallerName { get; set; }
        public string IncidentDate { get; set; }
        public string IncidentNature { get; set; }
        public string Initials { get; set; }
        public string County { get; set; }
        public string Drill { get; set; }
        public string Incident_Contractor_Or_Employee { get; set; }
        public string IndividualSafety { get; set; }
        public string WeaponReported { get; set; }
        public string WeaponType { get; set; }
        public string wpviolence { get; set; }
        public string FacilityOrProject { get; set; }
        public string RegionOrFacility { get; set; }
        public string ContractorName { get; set; }
        public string FacilityOrProjectSelection { get; set; }
        public string OccuredOnPipeline { get; set; }
        public string NotificationDate { get; set; }
        public string NotificationTime { get; set; }
        public string PC_CWLocOrTransport { get; set; }
        public string SusAct { get; set; }
        public string SpillOrReleaseIntoAtmo { get; set; }
        public string MaterialSpilled { get; set; }
        public string WaterbodiesImpacted { get; set; }
        public string ContainedOnSite { get; set; }
        public string SpillContainedSecondary { get; set; }
        public string EmailSent { get; set; }

        //Pipeline Fields
        public string State { get; set; }
        public string Observing { get; set; }
        public string Date { get; set; }

        //811 Fields
        public string Time { get; set; }
        public string ExcavationDate { get; set; }
        public string ExcavationTime { get; set; }
        public string NormalOrEmergency { get; set; }
        public string RequestTicketNo { get; set; }
        public string PersonCompanyName { get; set; }
        public string CallbackNumber { get; set; }
        public string EmailAddress { get; set; }
        public string City { get; set; }
        public string WorkDate { get; set; }
        public string Street { get; set; }
        public string Intersection { get; set; }
        public string Nature { get; set; }
        public string Remarks { get; set; }
        public string FacilityName { get; set; }

        //Locked Gate Fields
        public string CallerNumber {get; set;}
        public string Name {get; set;}
        public string ContactNumber {get; set; }
        public string Location {get; set; }
    }
}

crm.chemtelinc.com/Controllers/CrestwoodController.cs
using ChemicalLibrary;
using crm.chemtelinc.com.Models;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using SendGrid;
using SendGrid.Helpers.Mail;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Microsoft.Office.Interop.Excel;
using OfficeOpenXml;

namespace crm.chemtelinc.com.Controllers
{
    public class CrestwoodController : Controller
    {
        public int id = 0;  //Used to determine if a report was opened from the log.  If so, this variable will hold the ID number of that report
        int tmpid = 0;  //Temp variable
        string ersop = "";
        string email = "";  //Holds the ESR member's email address.
        string drill = "";
        string filepath = ""; 
        bool emptyreport = false;  //Flag used to indicate whether the report form is empty, or if a report successfully submitted.  Flag is checked when the form closes.
        string pipelineemail = ",AssetType-Pipeline@crestwoodlp.com";  //Class-level variable that holds the ESR member's email address so it can be passed to the email form.
        string CCemail = "";  //Class-level variable that holds the CC email address(es) so it can be passed to the email form.
        string initials = "";
        string NERegion = ",AL,CO,DE,DC,FL,GA,IN,KY,ME,MA,MI,MS,NH,NJ,NY,NC,OH,PA,RI,SC,TN,VT,VA,WV,";
        string CentralRegion = ",AZ,AR,IL,IA,KS,LA,MN,MO,NB,NM,OK,TX,UT,WI,";
        string NorthRegion = ",AK,CA,HI,ID,MT,NV,ND,OR,SD,WA,WY,";


        #region Log Functions
        public ActionResult CrestwoodLogs()
        {
            string LogType = Request.QueryString["SelectedLog"].ToString();
            ViewBag.LogSelected = LogType;
            List<CrestwoodLog> CrestLogList = new List<CrestwoodLog>();

            if (LogType == "GeneralIncident")
            {
                string sqlcmd = "SELECT TOP 100 * FROM crestgeneralincidents ORDER BY id DESC";
                using (SqlConnection con = new SqlConnection(Session["constring"].ToString()))
                {
                    using (SqlCommand cmd = new SqlCommand(sqlcmd, con))
                    {
                        con.Open();
                        SqlDataReader sdr = cmd.ExecuteReader();
                        while (sdr.Read())
                        {
                            CrestwoodLog c = new CrestwoodLog();
                            c.id = Int32.Parse(sdr["id"].ToString());
                            c.CallerName = sdr["CallerName"].ToString();
                            c.IncidentDate = sdr["IncidentDate"].ToString();
                            c.IncidentNature = sdr["IncidentNature"].ToString();
                            c.Initials = sdr["Initials"].ToString();
                            c.County = sdr["County"].ToString();
                            c.Drill = sdr["Drill"].ToString();
                            c.Incident_Contractor_Or_Employee = sdr["Incident_Contractor_Or_Employee"].ToString();
                            c.IndividualSafety = sdr["IndividualSafety"].ToString();
                            c.WeaponReported = sdr["WeaponReported"].ToString();
                            c.WeaponType = sdr["WeaponType"].ToString();
                            c.wpviolence = sdr["wpviolence"].ToString();
                            c.FacilityOrProject = sdr["FacilityOrProject"].ToString();
                            c.RegionOrFacility = sdr["RegionOrFacility"].ToString();
                            c.ContractorName = sdr["ContractorName"].ToString();
                            c.FacilityOrProjectSelection = sdr["FacilityOrProjectSelection"].ToString();
                            c.OccuredOnPipeline = sdr["OccuredOnPipeline"].ToString();
                            c.NotificationDate = sdr["NotificationDate"].ToString();
                            c.NotificationTime = sdr["NotificationTime"].ToString();
                            c.PC_CWLocOrTransport = sdr["PC_CWLocOrTransport"].ToString();
                            c.SusAct = sdr["SusAct"].ToString();
                            c.SpillOrReleaseIntoAtmo = sdr["SpillOrReleaseIntoAtmo"].ToString();
                            c.MaterialSpilled = sdr["MaterialSpilled"].ToString();
                            c.WaterbodiesImpacted = sdr["WaterbodiesImpacted"].ToString();
                            c.ContainedOnSite = sdr["ContainedOnSite"].ToString();
                            c.SpillContainedSecondary = sdr["SpillContainedSecondary"].ToString();
                            c.EmailSent = sdr["EmailSent"].ToString();
                            CrestLogList.Add(c);
                        }
                    }
                }
                return View(CrestLogList.ToList());
            } else if (LogType == "Pipeline")
            {
                string sqlcmd = "SELECT TOP 100 * FROM crestpiplineincidents ORDER BY id DESC";
                using (SqlConnection con = new SqlConnection(Session["constring"].ToString()))
                {
                    using (SqlCommand cmd = new SqlCommand(sqlcmd, con))
                    {
                        con.Open();
                        SqlDataReader sdr = cmd.ExecuteReader();
                        while (sdr.Read())
                        {
                            CrestwoodLog c = new CrestwoodLog();
                            c.id = Int32.Parse(sdr["id"].ToString());
                            c.County = sdr["County"].ToString();
                            c.State = sdr["State"].ToString();
                            c.Observing = sdr["Observing"].ToString();
                            c.Date = sdr["Date"].ToString();
                            c.Initials = sdr["Initials"].ToString();
                            c.NotificationDate = sdr["NotificationDate"].ToString();
                            c.NotificationTime = sdr["NotificationTime"].ToString();
                            c.Drill = sdr["Drill"].ToString();
                            c.EmailSent = sdr["EmailSent"].ToString();
                            CrestLogList.Add(c);
                        }
                    }
                }
                return View(CrestLogList.ToList());
            }
            
            else if (LogType == "811") {
                string sqlcmd = "SELECT TOP 100 * FROM crest811 WHERE requestticketnumber != '' ORDER BY id DESC";
                using (SqlConnection con = new SqlConnection(Session["constring"].ToString()))
                {
                    using (SqlCommand cmd = new SqlCommand(sqlcmd, con))
                    {
                        con.Open();
                        SqlDataReader sdr = cmd.ExecuteReader();
                        while (sdr.Read())
                        {
                            CrestwoodLog c = new CrestwoodLog();
                            c.id = Int32.Parse(sdr["id"].ToString());
                            c.Date = sdr["todaydate"].ToString();
                            c.Time = sdr["todaytime"].ToString();
                            c.ExcavationDate = sdr["excavationdate"].ToString();
                            c.ExcavationTime = sdr["excavationtime"].ToString();
                            c.NormalOrEmergency = sdr["normaloremergency"].ToString();
                            c.RequestTicketNo = sdr["requestticketnumber"].ToString();
                            c.PersonCompanyName = sdr["personcompanyname"].ToString();
                            c.CallbackNumber = sdr["callbacknumber"].ToString();
                            c.EmailAddress = sdr["emailaddress"].ToString();
                            c.City = sdr["city"].ToString();
                            c.State = sdr["state"].ToString();
                            c.County = sdr["county"].ToString();
                            c.WorkDate = sdr["workdate"].ToString();
                            c.Street = sdr["street"].ToString();
                            c.Intersection= sdr["intersection"].ToString();
                            c.Nature= sdr["nature"].ToString();
                            c.Remarks= sdr["remarks"].ToString();
                            c.FacilityName = sdr["FacilityName"].ToString();
                            CrestLogList.Add(c);
                        }
                    }
                }
                return View(CrestLogList.ToList());
            } else if (LogType == "LockedGate")
            {
                string sqlcmd = "SELECT id, callername, callernumber, state, county, name, contactnumber, location FROM crest811 WHERE state !='' AND county !='' AND callername !='' AND callernumber !='' AND name !=''AND contactnumber !='' AND location !='' ORDER BY id DESC";
                using (SqlConnection con = new SqlConnection(Session["constring"].ToString()))
                {
                    using (SqlCommand cmd = new SqlCommand(sqlcmd, con))
                    {
                        con.Open();
                        SqlDataReader sdr = cmd.ExecuteReader();
                        while (sdr.Read())
                        {
                            CrestwoodLog c = new CrestwoodLog();
                            c.id = Int32.Parse(sdr["id"].ToString());
                            c.CallerName = sdr["callername"].ToString();
                            c.CallerNumber = sdr["callernumber"].ToString();
                            c.State = sdr["state"].ToString();
                            c.County = sdr["county"].ToString();
                            c.Name = sdr["name"].ToString();
                            c.ContactNumber = sdr["contactnumber"].ToString();
                            c.Location = sdr["location"].ToString();
                            CrestLogList.Add(c);
                        }

crm.chemtelinc.com/Views/Crestwood/CrestwoodLogs.cshtml
@model IList<crm.chemtelinc.com.Models.CrestwoodLog>
@{
    ViewBag.Title = "CrestwoodLogs";
    string LogSelected = ViewBag.LogSelected;
}
@if (LogSelected == "GeneralIncident" || LogSelected == "Pipeline")
{

    <div id="reportsearchcontainer" style="width: 49%;display:inline-block;vertical-align:top; text-align:center;">
        @using (Html.BeginForm("ReportLogSearch", "Crestwood", FormMethod.Post, new { id = "ReportSearchForm" }))
        {
            <span>Report Search</span>
            <hr />
            <br />
            <input type="text" name="reportid" id="reportid" class="form-control GLOFieldSpacing" style="width:30%;" placeholder="ID #" />
            <input type="hidden" name="submittype" id="submittype" />
            <input type="hidden" name="logtype" id="logtype" value="@LogSelected" />
            <input type="button" value="Search" class="form-control GLOFieldSpacing" style="width:20%;" onclick="Search()" />
            <input type="button" value="Refresh" class="form-control GLOFieldSpacing" style="width: 20%;" onclick="ViewPDF()" />
            <input type="button" value="Revise" class="form-control GLOFieldSpacing" style="width: 20%;" onclick="Revise()" />
        }
    </div>
    <div id="generatereportcontainer" style="width: 50%; display: inline-block; text-align: center;">
        <span>Monthly Report</span>
        <hr />
        <div style="display: inline-block; width: 50%;">
            <span>Start Date:</span>
            <input type="date" name="startdate" id="startdate" class="form-control GLOFieldSpacing" style="width:60%;" />
            <br />
            <span>End Date:</span>
            <input type="date" name="enddate" id="enddate" class="form-control GLOFieldSpacing" style="width:60%;" />
            <input type="button" value="Generate Report" class="form-control GLOFieldSpacing" onclick="GenerateReport('@LogSelected')" />
        </div>
    </div>
    <hr />
}

@if (LogSelected == "GeneralIncident")
{
    <h2 style="text-align:center;">Crestwood General Incident Logs</h2>
    <br />
    <table cellpadding="3" style="width: 100%; max-width:!important none; ">
        <tr>
            <th></th>
            <th class="LogTableHeaders">id</th>
            <th class="LogTableHeaders">CallerName</th>
            <th class="LogTableHeaders">Incident Date</th>
            <th class="LogTableHeaders">Incident Nature</th>
            <th class="LogTableHeaders">Initials</th>
            <th class="LogTableHeaders">County</th>
            <th class="LogTableHeaders">Drill</th>
            <th class="LogTableHeaders">Incident_Contractor_Or_Employee</th>
            <th class="LogTableHeaders">IndividualSafety</th>
            <th class="LogTableHeaders">WeaponReported</th>
            <th class="LogTableHeaders">WeaponType</th>
            <th class="LogTableHeaders">wpviolence</th>
            <th class="LogTableHeaders">FacilityOrProject</th>
            <th class="LogTableHeaders">RegionOrFacility</th>
            <th class="LogTableHeaders">ContractorName</th>
            <th class="LogTableHeaders">FacilityOrProjectSelection</th>
            <th class="LogTableHeaders">OccuredOnPipeline</th>
            <th class="LogTableHeaders">NotificationDate</th>
            <th class="LogTableHeaders">NotificationTime</th>
            <th class="LogTableHeaders">PC_CWLocOrTransport</th>
            <th class="LogTableHeaders">SusAct</th>
            <th class="LogTableHeaders">SpillOrReleaseIntoAtmo</th>
            <th class="LogTableHeaders">MaterialSpilled</th>
            <th class="LogTableHeaders">WaterbodiesImpacted</th>
            <th class="LogTableHeaders">ContainedOnSite</th>
            <th class="LogTableHeaders">SpillContainedSecondary</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr id="Row_@item.id">
                <td><input type="radio" name="IDSelected" value="@item.id" onclick="FillTCEQID(this.value)" /></td>
                <td style="width:10%">
                    @if (item.EmailSent == "1") //Email was sent
                    {
                        <span style="color:green">&#10003;</span>
                    }
                    else if (item.EmailSent == "0") // Email has not been sent
                    {
                        <span style="color:red">&#x2715;</span>
                    }
                    else // value is null due to it being a new field.
                    {
                        <span style="color:yellow">&#9711;</span>
                    }
                    &nbsp;@item.id
                </td>
                <td>@item.CallerName</td>
                <td>@item.IncidentDate.Split(' ')[0]</td>
                <td>@item.IncidentNature</td>
                <td><input type="text" id="Initials_@item.id" value="@item.Initials" style="width:100%;" /><br /><br /><input type="button" value="Update" onclick="UpdateCrestInitials(@item.id)"/></td>
                <td>@item.County</td>
                <td>@item.Drill</td>
                <td>@item.Incident_Contractor_Or_Employee</td>
                <td>@item.IndividualSafety</td>
                <td>@item.WeaponReported</td>
                <td>@item.WeaponType</td>
                <td>@item.wpviolence</td>
                <td>@item.FacilityOrProject</td>
                <td>@item.RegionOrFacility</td>
                <td>@item.ContractorName</td>
                <td>@item.FacilityOrProjectSelection</td>
                <td>@item.OccuredOnPipeline</td>
                <td>@item.NotificationDate</td>
                <td>@item.NotificationTime</td>
                <td>@item.PC_CWLocOrTransport</td>
                <td>@item.SusAct</td>
                <td>@item.SpillOrReleaseIntoAtmo</td>
                <td>@item.MaterialSpilled</td>
                <td>@item.WaterbodiesImpacted</td>
                <td>@item.ContainedOnSite</td>
                <td>@item.SpillContainedSecondary</td>
            </tr>
        }
    </table>
}
else if (LogSelected == "Pipeline")
{
    <h2>Crestwood Pipeline Logs</h2>
    <br />
    <table cellpadding="3" style="width: 100%; max-width:!important none; ">
        <tr>
            <th class="LogTableHeaders"></th>
            <th class="LogTableHeaders">id</th>
            <th class="LogTableHeaders">Initials</th>
            <th class="LogTableHeaders">County</th>
            <th class="LogTableHeaders">State</th>
            <th class="LogTableHeaders">Observing</th>
            <th class="LogTableHeaders">Date</th>
            <th class="LogTableHeaders">NotificationDate</th>
            <th class="LogTableHeaders">NotificationTime</th>
            <th class="LogTableHeaders">Drill</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr id="Row_@item.id">
                <td><input type="radio" name="IDSelected" value="@item.id" onclick="FillTCEQID(@item.id)" /></td>
                <td style="width:10%">
                    @if (item.EmailSent == "1") //Email was sent
                    {
                        <span style="color:green">&#10003;</span>
                    }
                    else if (item.EmailSent == "0") // Email has not been sent
                    {
                        <span style="color:red">&#x2715;</span>
                    }
                    else // value is null due to it being a new field.
                    {
                        <span style="color:yellow">&#9711;</span>
                    }
                    &nbsp;@item.id
                </td>
                <td><input type="text" id="Initials_@item.id" value="@item.Initials" style="width:50%;" /><br /><br /><input type="button" value="Update" onclick="UpdateCrestInitials(@item.id)"/></td>
                <td>@item.County</td>
                <td>@item.State</td>
                <td>@item.Observing</td>
                <td>@item.Date.Split(' ')[0]</td>
                <td>@item.NotificationDate</td>
                <td>@item.NotificationTime</td>
                <td>@item.Drill</td>
            </tr>
        }
    </table>
}
else if (LogSelected == "811")
{
    <h2>811 Logs</h2>
    <br />
    <table cellpadding="3" style="width: 100%; max-width:!important none; border:1px solid black;">
        <tr>
            <th class="LogTableHeaders">ID</th>
            <th class="LogTableHeaders">Date</th>
            <th class="LogTableHeaders">Time</th>
            <th class="LogTableHeaders">Excavation Date</th>
            <th class="LogTableHeaders">Excavation Time</th>
            <th class="LogTableHeaders">Normal or Emergency</th>
            <th class="LogTableHeaders">Request Ticket Number</th>
            <th class="LogTableHeaders">Person Company Name</th>
            <th class="LogTableHeaders">Callback Number</th>
            <th class="LogTableHeaders">Email Address</th>
            <th class="LogTableHeaders">City</th>
            <th class="LogTableHeaders">State</th>
            <th class="LogTableHeaders">County</th>
            <th class="LogTableHeaders">Work Date</th>
            <th class="LogTableHeaders">Street</th>
            <th class="LogTableHeaders">Intersection</th>
            <th class="LogTableHeaders">Nature</th>
            <th class="LogTableHeaders">Remarks</th>
            <th class="LogTableHeaders">Facility Name</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td style="font-weight:bold;">@item.id</td>
                <td>@item.Date</td>
                <td>@item.Time</td>
                <td>@item.ExcavationDate</td>
                <td>@item.ExcavationTime</td>
                <td>@item.NormalOrEmergency</td>
                <td>@item.RequestTicketNo</td>
                <td>@item.PersonCompanyName</td>
                <td>@item.CallbackNumber</td>
                <td>@item.EmailAddress</td>
                <td>@item.City</td>
                <td>@item.State</td>
                <td>@item.County</td>
                <td>@item.WorkDate</td>
                <td>@item.Street</td>
                <td>@item.Intersection</td>
                <td>@item.Nature</td>
                <td>@item.Remarks</td>
                <td>@item.FacilityName</td>
            </tr>
        }
    </table>
}
else if (LogSelected == "LockedGate")
{
    <h2>Locked Gate Access Logs</h2>
    <br />
    <table cellpadding="5" style="width: 100%; max-width:!important none; ">
        <tr>
            <th class="LogTableHeaders">ID</th>
            <th class="LogTableHeaders">Caller Name</th>
            <th class="LogTableHeaders">Caller Number</th>
            <th class="LogTableHeaders">State</th>
            <th class="LogTableHeaders">County</th>
            <th class="LogTableHeaders">Name</th>
            <th class="LogTableHeaders">Contact Number</th>
            <th class="LogTableHeaders">Location</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.id</td>
                <td>@item.CallerName</td>
                <td>@item.CallerNumber</td>
                <td>@item.State</td>
                <td>@item.County</td>
                <td>@item.Name</td>
                <td>@item.ContactNumber</td>
                <td>@item.Location</td>
            </tr>
        }
    </table>
}
<p>
    <span style="color:green">&#10003;</span> - Email has been sent. <br />
    <span style="color:red">&#x2715;</span> - Email has NOT been sent. <br />
    <span style="color:yellow">&#9711;</span> - Unable to track if email was sent.
</p>
<script>
    function GenerateReport() {
        var x = document.getElementById('startdate').value;
        var y = document.getElementById('enddate').value;
        return true;
    }
    function Search() {
        document.getElementById("submittype").value = "Search";
        document.getElementById("ReportSearchForm").submit();

    }
    function ViewPDF() {
        location.reload();
    }
    function Revise() {
        document.getElementById("submittype").value = "Revise";
        document.getElementById("ReportSearchForm").submit();
    }
    function FillTCEQID(id) {
        document.getElementById("reportid").value = id;
    }
    function UpdateCrestInitials(id) {
        var NewInitials = document.getElementById('Initials_' + id).value;

        $.ajax({
            url: '/Crestwood/UpdateCrestwoodInitials',
            data: { IncidentID: id, Initials: NewInitials, ReportType: "@LogSelected" },
            type: 'GET',
            success: function (data) {
                alert("The report has been updated.");
            },
            error: function (date) {
                alert("ERROR!");
            }
        })
    }

    function GenerateReport(LogType) {
        $.ajax({
            url: '/Crestwood/GenerateReport',
            data: { StartDate: document.getElementById('startdate').value, EndDate: document.getElementById('enddate').value, ReportType: LogType },
            type: 'GET',
            success: function (data) {
                alert("Report Generated Successfully!");
                window.open(data.file);
            },
            error: function (date) {
                alert("ERROR!");
            }
        })
    }

</script>

crm.chemtelinc.com/Views/Crestwood/LockedGateReport.cshtml
@{
    string constring = crm.chemtelinc.com.Properties.Settings.Default.StatesConnectionString;
    ViewBag.Title = "LockedGateReport";
    List<string> States = new List<string>();
    List<string> Names = new List<string>();
    States = ChemicalLibrary.Search.GetStates(constring);
    Names = ViewBag.Names;
}

<h2>Crestwood Locked Gate Report</h2>


@using (Html.BeginForm("SubmitLockedGateReport", "Crestwood", FormMethod.Post))
{
    <div id="CrestLockedGateReportContainer" style="font-size: 10pt;">
        <div id="FormButtons" style="padding:2%;text-align:right;">
            <input type="submit" value="Submit" class="form-control GRCPButtons required-field" id="btnsubmit" name="btnsubmit" tabindex="99">
            <input type="button" value="Close" class="form-control GRCPButtons alert-info" id="btnclose" name="btnclose" onclick="ClearForm()">
        </div>

        <div id="LockedGateForm" style="width: 40%;text-align:left;margin: 0 auto;">
            @if (Request.QueryString["Result"] != null && Request.QueryString["Result"] == "Success")
            {
                <span class="alert-success">Record Added Successfully!</span><br />
            }
            <span class="required-field">Callers Name</span><input type="text" class="form-control GLOFieldSpacing" id="txtcallername" name="txtcallername" required="" style="width:80%" tabindex="1" /> <br />
            <span>Callers Number</span><input type="text" class="form-control GLOFieldSpacing" id="txtcallernumber" name="txtcallernumber" placeholder="(___) ___-____" style="width:30%" tabindex="2" onblur="FormatPhone(this.value, this.id)" /> <br />
            <span class="required-field">State</span>
            <select class="GLOFieldSpacing" name="txtstate" id="txtstate" required="" tabindex="3">
                <option value="" selected=""></option>
                @foreach (string st in States)
                {
                    <option value="@st">@st</option>
                }
            </select><br />
            <span class="required-field">County</span><input type="text" class="form-control GLOFieldSpacing" id="txtcounty" name="txtcounty" style="width:80%" required="" tabindex="4" /> <br />
            <span class="required-field">Facility Name</span><input type="text" class="form-control GLOFieldSpacing" id="FacilityName" name="FacilityName" style="width:80%" required="" tabindex="5" /> <br />
        </div>
        <br />
        <div style="text-align:center;">
            <div class="CrestInlineDisplay">
                <span class="required-field">Name</span><br />

                @Html.TextBox("txtname", "", new { @class = "GLOFieldSpacing", id = "txtname", onchange = "GetInfo(this.value)", list = "ERSMembers" })

            </div>
            <div class="CrestInlineDisplay" style="width:20%;">
                <span>Contact Number</span><br />
                <input type="text" class="form-control GLOFieldSpacing" id="txtcontactnumber" name="txtcontactnumber" tabindex="7" onblur="FormatPhone(this.value, this.id)" />
            </div>
            <div class="CrestInlineDisplay" style="width:20%;">
                <span class="required-field">Location</span><br />
                <input type="text" class="form-control GLOFieldSpacing" id="txtlocation" name="txtlocation" required="" tabindex="8" />
            </div>
        </div>
    </div>

    <datalist id="ERSMembers">
        @foreach (string n in Names)
        {
            var temp = n.Split('_');
            string nameId = temp[1];
            string name = temp[0];
            <option value="@n">@name</option>
        }
    </datalist>
}

<script>
    // clear form
    function ClearForm() {
        if (confirm("Are you sure you want to cancel this report?")) {
            document.getElementById("txtcallername").value = "";
            document.getElementById("txtcallernumber").value = "";
            document.getElementById("txtstate").selectedIndex = 0;
            document.getElementById("txtcounty").value = "";
            document.getElementById("FacilityName").value = "";
            document.getElementById("txtname").selectedIndex = 0;
            document.getElementById("txtcontactnumber").value = "";
            document.getElementById("txtlocation").value = "";
        }
    }

    function FormatPhone(Phone, FieldName) {
        //Purely number input, no parenthesis, no hyphens.
        if (Phone.length == 10 && !Phone.includes("-") && !Phone.includes("(") && !Phone.includes(")")) {
            var ps = Phone.split("");
            var fullphone = "(" + ps[0] + ps[1] + ps[2] + ") " + ps[3] + ps[4] + ps[5] + "-" + ps[6] + ps[7] + ps[8] + ps[9]
            document.getElementById(FieldName).value = fullphone;
        }
    }

    //get ers members phone number and location
    function GetInfo(NameID) {
        //separate name and ID to get the phone and location
        var id = NameID.split('_');
        id = id[1];

        $.ajax({
            url: '/Crestwood/SearchByID/',
            data: { ID: id },
            type: 'GET',
            success: function (data) {
                var phoneLoc = data.split('_');
                document.getElementById("txtcontactnumber").value = phoneLoc[0];
                document.getElementById("txtlocation").value = phoneLoc[1];
            },
            error: function (data) {
                alert("ERROR!");
            }
        });
        document.getElementById("txtname").value = NameID.split('_')[0];
    }
</script>