crm.chemtelinc.com/Models/NorthwindLog.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChemicalLibrary
{
    public class NorthwindLog
    {
        public int id { get; set; }
        public string ERSOperator { get; set; }
        public string CallerName { get; set; }
        public string CallerPhone { get; set; }
        public string Incident_Contractor_Or_Employee { get; set; }
        public string ContractedCompany { get; set; }
        public string CallDate { get; set; }
        public string CallTime { get; set; }
        public string IncidentDate { get; set; }
        public string IncidentTime { get; set; }
        public string IncidentTimeZone { get; set; }
        public string IncidentCity { get; set; }
        public string FacilityOrProject { get; set; }
        public string IncidentLocation { get; set; }
        public string IncidentNature { get; set; }
        public string WaterBodiesImpacted { get; set; }
        public string ImpactedArea { get; set; }
        public string IncidentDetails { get; set; }
        public string IndividualSafety { get; set; }
        public string Notify911 { get; set; }
        public string TransportToHospital { get; set; }
        public string MediaOnScene { get; set; }
        public string EMSOnScene { get; set; }
        public string HSERName { get; set; }
        public string HSERPhone { get; set; }
        public string InjuryExposureIllness { get; set; }
        public string ChemicalSpillRelease { get; set; }
        public string NotificationDate { get; set; }
        public string NotificationTime { get; set; }
        public string EmailSent { get; set; }

        //Pipeline Fields
        public string State { get; set; }
        public string Observing { get; set; }
        public string Date { get; set; }
        public string FacilityOrProjectSelection { get; set; }
        public string County { get; set; }
    }
}

crm.chemtelinc.com/Controllers/NorthwindController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using ChemicalLibrary;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using SendGrid;
using SendGrid.Helpers.Mail;
using ChemicalLibrary;

namespace crm.chemtelinc.com.Controllers
{
    public class NorthwindController : Controller
    {
        string constring = Properties.Settings.Default.chemicalConnectionString;
        // GET: Northwind
        #region Get Views
        public ActionResult GeneralIncident()
        {
            if (Session["Username"] == null || Session["Username"].ToString() == "")
            {
                ViewBag.ErrorMessage = "You must login before proceeding!";
                return RedirectToAction("Index", "Home", new { e = "You must login before proceeding!" });
            }
            return View(new NorthwindGenInc());
        }

        public ActionResult Pipeline()
        {
            if (Session["Username"] == null || Session["Username"].ToString() == "")
            {
                ViewBag.ErrorMessage = "You must login before proceeding!";
                return RedirectToAction("Index", "Home", new { e = "You must login before proceeding!" });
            }
            return View(new NorthwindPipeline());
        }

        public ActionResult EmailForm(NorthwindEmail n)
        {
            return View(n);
        }
        #endregion

        #region Form Submissions
        public ActionResult SubmitNewGenIncReport(FormCollection fc)
        {
            NorthwindGenInc ngi = new NorthwindGenInc();
            ngi = GetGenIncData(fc);

            if (fc["Revised"].ToString() != "true")
            {
                Add.AddNorthwindGenInc(Session["constring"].ToString(), ngi); //Add new report data to the database.
                ngi.ID = GetLatestGenIncID();
            } else
            {
                ngi.ID = Int32.Parse(fc["ReportID"].ToString());
                Update.UpdateNorthindGeneralIncident(Session["constring"].ToString(), ngi);
            }
            //start prep for email autopopulation.
            NorthwindEmail nwe = new NorthwindEmail();
            DateTime callDate = ngi.Call_Date;
            DateTime callTime = DateTime.Parse(ngi.Call_Time);
            DateTime incidentDate = ngi.Incident_Date;
            DateTime incidentTime = DateTime.Parse(ngi.Incident_Time);
            DateTime notificationDate = ngi.NotificationDate;
            DateTime notificationTime = DateTime.Parse(ngi.NotificationTime);


            string filepath = CreateGenIncReport(ngi.ID, ngi.Call_Date.Year.ToString());


            nwe.ID = ngi.ID;
            nwe.ReportType = "General Incident";
            nwe.FilePath = filepath;
            nwe.ToEmails = "mpepitone@ehs.com,ers@ehs.com,ben@nwmidstream.com,dbarton@nwmidstream.com,agarza@nwmidstream.com,emiller@nwmidstream.com,rregister@nwmidstream.com,ssanders@nwmidstream.com,jsouthard@nwmidstream.com,jsisk@nwmidstream.com,jyamartino@nwmidstream.com";
            if (ngi.IncidentType == "Vehicle Accident")
            {
                nwe.ToEmails += ",egarza@nwmidstream.com,npeters@nwmidstream.com";
            }
            nwe.Subject = "Incident Notification: ";
            if (fc["ddlFacilityOrProject"].ToString() == "Yes")
            {
                nwe.Subject += callDate.ToString("yyyyMMdd") + " | " + ngi.IncidentLocation + " | " + ngi.IncidentType;
            }
            else
            {
                nwe.Subject += callDate.ToString("yyyyMMdd") + " | " + ngi.Incident_City + ", " + ngi.Incident_State + " | " + ngi.IncidentType;
            }
            nwe.Body = "The Northwind Incident Hotline was notified at " + ngi.NotificationTime + " EST that at approximately " + ngi.Incident_Time + " " +ngi.Incident_Time_Zone + " on " + incidentDate.ToString("yyyy-MM-dd") + ", " +
               ngi.IncidentDetails + ". This occurred at " + ngi.IncidentLocation + " near " + ngi.Incident_City + ", " + ngi.Incident_State + ".";
            if (ngi.InjuryExposureIllness == "Yes")
            {
                nwe.Body += " There was a report of an injury, exposure, or illness associated with this incident.";
            } else
            {
                nwe.Body += " There were no injuries reported.";
            }
            if (ngi.ChemicalSpillRelease == "Yes") //If there was a chemical/product spill/release
            {
                nwe.Body += " There was a report of a chemical/product spill/release.";
                if (ngi.WaterbodiesImpacted == "Yes") //If there were bodies 
                {
                    nwe.Body += " The spill/release did impact one or more water bodies. " + ngi.ImpactedAreas + ".";
                }
            } else
            {
                nwe.Body += " There was no reported spill/release.";
            }
            nwe.Body += " An incident report will be initiated within the Northwind Incident Management System and assigned to the EHSR Advisor for update and completion.";
            return View("EmailForm", nwe);
        }

        public ActionResult SubmitNewPipelineReport(FormCollection fc)
        {
            NorthwindPipeline n = new NorthwindPipeline();
            NorthwindEmail nwe = new NorthwindEmail();
            n = GetPipelineData(fc);

            if (fc["Revised"].ToString() != "true") //New report
            {
                Add.AddNorthwindPipeline(Session["constring"].ToString(), n);
                n.ID = GetLatestPipelineID(); // Gets and sets the new ID that was just entered.
            }
            else // Updated report (user clicked Back To Report button)
            {
                n.ID = Int32.Parse(fc["ReportID"].ToString());
                Update.UpdateNorthwindPipeline(Session["constring"].ToString(), n);
            }
            string filepath = CreatePipelineReport(n.ID, n.Call_Date.Year.ToString());
            string LocationString = "";
            if (n.City == "UNK")
            {
                LocationString = n.ClosestLandmark;
            }
            else
            {
                LocationString = n.City;
            }


            nwe.ID = n.ID;
            nwe.ReportType = "Pipeline";
            nwe.ToEmails = "mpayne@nwmidstream.com,rregister@nwmidstream.com,avillalobos@nwmidstream.com,ben@nwmidstream.com,emiller@nwmidstream.com,jsouthard@nwmidstream.com,dbarton@nwmidstream.com,jyamartino@nwmidstream.com,klewis@nwmidstream.com,jsisk@nwmidstream.com,mpepitone@ehs.com,ers@ehs.com";
            nwe.FilePath = filepath;
            nwe.Subject = "Pipeline Incident Notification: " + n.Call_Date.ToString("yyyyMMdd") + " " + n.County + ", " + n.State;
            nwe.Body = "Northwind's Pipeline Emergency Hotline was notified at: " + DateTime.Parse(n.Call_Time).ToString("HH:mm") + " of a potential incident located in " + n.County + ", " + n.State + " near " + LocationString
                 + ". Northwind personnel have been notified of the situation and are currently investigating the report." +
                " Additional details are attached to this email.";
            return View("EmailForm", nwe);
        }

        public ActionResult SendNorthwindEmail(FormCollection fc)
        {
            var client = new SendGridClient("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");
            var from = new EmailAddress("ers@ehs.com");
            string[] emails = fc["txtToEmails"].ToString().Split(',');
            string body = fc["txtBody"].ToString();
            string subject = fc["txtSubject"].ToString();
            List<EmailAddress> to = new List<EmailAddress>();
            foreach (string email in emails)
            {
                if (email.Trim() != null && email.Trim() != "")
                {
                    to.Add(new EmailAddress(email.Trim()));
                }
            }
            to.Add(new EmailAddress("ers@ehs.com"));
            to.Add(new EmailAddress("mpepitone@ehs.com"));
            var msg = MailHelper.CreateSingleEmailToMultipleRecipients(from, to, subject, "", body, true);
            //Attach Saved PDF to email
            var filename = Path.GetFileName(fc["txtFilePath"].ToString());
            var bytes = System.IO.File.ReadAllBytes(fc["txtFilePath"].ToString()); //Get Attachment Bytes
            var file = Convert.ToBase64String(bytes);
            msg.AddAttachment(filename, file); //Add Attachment to email.
            var response = client.SendEmailAsync(msg);

            string ResultCode = response.Result.StatusCode.ToString();

            if (ResultCode == "Accepted")
            {
                if (fc["ReportType"] == "General Incident")
                {
                    Update.UpdateEmailSent("NorthwindGeneralIncidents", "ID", fc["reportid"].ToString(), Session["constring"].ToString());
                } else
                {
                    Update.UpdateEmailSent("NorthwindPipelineIncidents", "ID", fc["reportid"].ToString(), Session["constring"].ToString());
                }
            }

            return RedirectToAction("Index", "Home", new { Result = ResultCode });
        }

        public ActionResult BackToReport(FormCollection fc)
        {
            ViewBag.Revised = "true";
            if (fc["ReportType"].ToString() == "Pipeline")
            {
                NorthwindPipeline nwp = new NorthwindPipeline(Session["constring"].ToString(), int.Parse(fc["reportid"].ToString()));  //Gets the desired report and puts it into a custom class variable.
                return View("Pipeline", nwp);
            } else
            {
                NorthwindGenInc ngi = new NorthwindGenInc(Session["constring"].ToString(), int.Parse(fc["reportid"].ToString()));
                return View("GeneralIncident", ngi);
            }
        }
        #endregion

crm.chemtelinc.com/Views/Northwind/EmailForm.cshtml
@model ChemicalLibrary.NorthwindEmail
@{
    ViewBag.Title = "Northwind Email Form";
}

<h2>Northwind Email Form</h2>
<br />
@using (Html.BeginForm("BackToReport", "Northwind", FormMethod.Post))
{
    <input type="hidden" value="@Model.ID" name="reportid" id="reportid" />
    <input type="hidden" value="@Model.ReportType" name="ReportType" />
    <input type="submit" value="Back To Report" name="UpdateOrCorrect" />
}
<br />
@using (Html.BeginForm("SendNorthwindEmail", "Northwind", FormMethod.Post))
{
    <span>To Emails: </span> <input type="button" onclick="AddMVEmails()" class="form-control " style="width:10%;float:right;" value="Add MV Emails"/>
    @Html.TextBoxFor(m => m.ToEmails, new { @class = "form-control GLOFieldSpacing", id = "txtToEmails", @Name = "txtToEmails", required = "", tabindex = "1" })
    <br />
    <span>Email Subject: </span>@Html.TextBoxFor(m => m.Subject, new { @class = "form-control GLOFieldSpacing", id = "txtSubject", @Name = "txtSubject", required = "", tabindex = "2" })
    <br />
    <span>File Path: </span>@Html.TextBoxFor(m => m.FilePath, new { @class = "form-control GLOFieldSpacing", id = "txtFilePath", @Name = "txtFilePath", required = "", tabindex = "3" })
    <br />
    <span>Email Body: </span>@Html.TextAreaFor(m => m.Body, new { @class = "form-control GLOFieldSpacing", id = "txtBody", @Name = "txtBody", required = "", tabindex = "4", rows = "5" })
    <br />
    <br />
    <input type="hidden" value="@Model.ID" name="reportid" id="reportid" />
    <input type="hidden" value="@Model.ReportType" name="ReportType" />
    <input type="submit" name="SubmitEmail" value="Send Email" class="form-control GLOFieldSpacing" style="color:blue; font-weight:bold;" />
}

<script>
    $(document).ready(function () {
        var FilePath = "";
        if ("@Model.ReportType" == "Pipeline") {
            FilePath = "https://crm.chemtel.net/Completed Reports/Northwind Incidents/Pipeline/" + @DateTime.Now.Year.ToString() + "/Northwind Pipeline - " + @Model.ID + ".pdf";
        } else {
            FilePath = "https://crm.chemtel.net/Completed Reports/Northwind Incidents/General Incident/" + @DateTime.Now.Year.ToString() + "/Northwind GI - " + @Model.ID + ".pdf";
        }
        window.open(FilePath, "_blank");
    });


    function AddMVEmails() {
        $("#txtToEmails").val($("#txtToEmails").val() + ",egarza@nwmidstream.com,npeters@nwmidstream.com");
    }
</script>

crm.chemtelinc.com/Views/Northwind/NorthwindLogs.cshtml
@model IList<ChemicalLibrary.NorthwindLog>
@{
    ViewBag.Title = "Northwind Logs";
    string LogSelected = ViewBag.LogSelected;
}
@if (LogSelected == "GeneralIncident" || LogSelected == "Pipeline")
{

    <div id="reportsearchcontainer" style="width: 49%;display:inline-block;vertical-align:top; text-align:center;">
        @using (Html.BeginForm("ReportLogSearch", "Northwind", FormMethod.Post, new { id = "ReportSearchForm" }))
        {
            <span>Report Search</span>
            <hr />
            <br />
            <input type="text" name="reportid" id="reportid" class="form-control GLOFieldSpacing" style="width:30%;" placeholder="ID #" />
            <input type="hidden" name="submittype" id="submittype" />
            <input type="hidden" name="logtype" id="logtype" value="@LogSelected" />
            <input type="button" value="Search" class="form-control GLOFieldSpacing" style="width:20%;" onclick="Search()" />
            <input type="button" value="Refresh" class="form-control GLOFieldSpacing" style="width: 20%;" onclick="ViewPDF()" />
            <input type="button" value="Revise" class="form-control GLOFieldSpacing" style="width: 20%;" onclick="Revise()" />
        }
    </div>
    <div id="generatereportcontainer" style="width: 50%; display: inline-block; text-align: center;">
        <span>Monthly Report</span>
        <hr />
        <div style="display: inline-block; width: 50%;">
            <span>Start Date:</span>
            <input type="date" name="startdate" id="startdate" class="form-control GLOFieldSpacing" style="width:60%;" />
            <br />
            <span>End Date:</span>
            <input type="date" name="enddate" id="enddate" class="form-control GLOFieldSpacing" style="width:60%;" />
            <input type="button" value="Generate Report" class="form-control GLOFieldSpacing" onclick="GenerateReport('@LogSelected')" />
        </div>
    </div>
    <hr />
}

@if (LogSelected == "GeneralIncident")
{
    <h2 style="text-align:center;">Northwind General Incident Logs</h2>
    <br />
    <table cellpadding="3" style="width: 100%; max-width:!important none; ">
        <tr>
            <th></th>
            <th class="LogTableHeaders">ID</th>
            <th class="LogTableHeaders">ERS Operator</th>
            <th class="LogTableHeaders">Caller Name</th>
            <th class="LogTableHeaders">Caller Phone</th>
            <th class="LogTableHeaders">Employee or Contractor</th>
            <th class="LogTableHeaders">Contracted Company Name</th>
            <th class="LogTableHeaders">Call Date</th>
            <th class="LogTableHeaders">Call Time</th>
            <th class="LogTableHeaders">Incident Date</th>
            <th class="LogTableHeaders">Incident Time</th>
            <th class="LogTableHeaders">Incident Time Zone</th>
            <th class="LogTableHeaders">Incident City</th>
            <th class="LogTableHeaders">Incident State</th>
            <th class="LogTableHeaders">Facility or NW Project</th>
            <th class="LogTableHeaders">Incident Location</th>
            <th class="LogTableHeaders">Incident Nature</th>
            <th class="LogTableHeaders">Injury, Exposure, or Illness</th>
            <th class="LogTableHeaders">Chemical Spill</th>
            <th class="LogTableHeaders">Waterbodies Impacted</th>
            <th class="LogTableHeaders">Impacted Areas</th>
            <th class="LogTableHeaders">Incident Details</th>
            <th class="LogTableHeaders">Threat to Safety</th>
            <th class="LogTableHeaders">Notified 911</th>
            <th class="LogTableHeaders">Transport to Hospital</th>
            <th class="LogTableHeaders">Media on Scene</th>
            <th class="LogTableHeaders">EMS On Scene</th>
            <th class="LogTableHeaders">HSER Name</th>
            <th class="LogTableHeaders">HSER Number</th>
            <th class="LogTableHeaders">Notification Date</th>
            <th class="LogTableHeaders">Notification Time</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr id="Row_@item.id">
                <td><input type="radio" name="IDSelected" value="@item.id" onclick="FillTCEQID(this.value)" /></td>
                <td>
                    @if (item.EmailSent == "1") //Email was sent
                    {
                        <span style="color:green">&#10003;</span>
                    }
                    else if (item.EmailSent == "0") // Email has not been sent
                    {
                        <span style="color:red">&#x2715;</span>
                    }
                    else // value is null due to it being a new field.
                    {
                        <span style="color:yellow">&#9711;</span>
                    }
                    &nbsp;@item.id
                </td>
                <td>@item.ERSOperator</td>
                <td>@item.CallerName</td>
                <td>@item.CallerPhone</td>
                <td>@item.Incident_Contractor_Or_Employee</td>
                <td>@item.ContractedCompany</td>
                <td>@item.CallDate</td>
                <td>@item.CallTime</td>
                <td>@item.IncidentDate</td>
                <td>@item.IncidentTime</td>
                <td>@item.IncidentTimeZone</td>
                <td>@item.IncidentCity</td>
                <td>@item.State</td>
                <td>@item.FacilityOrProject</td>
                <td>@item.IncidentLocation</td>
                <td>@item.IncidentNature</td>
                <td>@item.InjuryExposureIllness</td>
                <td>@item.ChemicalSpillRelease</td>
                <td>@item.WaterBodiesImpacted</td>
                <td>@item.ImpactedArea</td>
                <td>@item.IncidentDetails</td>
                <td>@item.IndividualSafety</td>
                <td>@item.Notify911</td>
                <td>@item.TransportToHospital</td>
                <td>@item.MediaOnScene</td>
                <td>@item.EMSOnScene</td>
                <td>@item.HSERName</td>
                <td>@item.HSERPhone</td>
                <td>@item.NotificationDate</td>
                <td>@item.NotificationTime</td>
            </tr>
        }
    </table>
}
else if (LogSelected == "Pipeline")
{
    <h2>Northwind Pipeline Logs</h2>
    <br />
    <table cellpadding="3" style="width: 100%; max-width:!important none; ">
        <tr>
            <th class="LogTableHeaders"></th>
            <th class="LogTableHeaders">id</th>
            <th class="LogTableHeaders">County</th>
            <th class="LogTableHeaders">State</th>
            <th class="LogTableHeaders">Observing</th>
            <th class="LogTableHeaders">Call Date</th>
            <th class="LogTableHeaders">NotificationDate</th>
            <th class="LogTableHeaders">NotificationTime</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr id="Row_@item.id">
                <td><input type="radio" name="IDSelected" value="@item.id" onclick="FillTCEQID(@item.id)" /></td>
                <td style="width:10%">
                    @if (item.EmailSent == "1") //Email was sent
                    {
                        <span style="color:green">&#10003;</span>
                    }
                    else if (item.EmailSent == "0") // Email has not been sent
                    {
                        <span style="color:red">&#x2715;</span>
                    }
                    else // value is null due to it being a new field.
                    {
                        <span style="color:yellow">&#9711;</span>
                    }
                    &nbsp;@item.id
                </td>
                <td>@item.County</td>
                <td>@item.State</td>
                <td>@item.Observing</td>
                <td>@item.Date.Split(' ')[0]</td>
                <td>@item.NotificationDate</td>
                <td>@item.NotificationTime</td>
            </tr>
        }
    </table>
}
<p>
    <span style="color:green">&#10003;</span> - Email has been sent. <br />
    <span style="color:red">&#x2715;</span> - Email has NOT been sent. <br />
    <span style="color:yellow">&#9711;</span> - Unable to track if email was sent.
</p>

<script>
    function GenerateReport() {
        var x = document.getElementById('startdate').value;
        var y = document.getElementById('enddate').value;
        return true;
    }
    function Search() {
        document.getElementById("submittype").value = "Search";
        document.getElementById("ReportSearchForm").submit();

    }
    function ViewPDF() {
        location.reload();
    }
    function Revise() {
        document.getElementById("submittype").value = "Revise";
        document.getElementById("ReportSearchForm").submit();
    }
    function FillTCEQID(id) {
        document.getElementById("reportid").value = id;
    }
    @*function UpdateCrestInitials(id) {
        var NewInitials = document.getElementById('Initials_' + id).value;

        $.ajax({
            url: '/Crestwood/UpdateCrestwoodInitials',
            data: { IncidentID: id, Initials: NewInitials, ReportType: "@LogSelected" },
            type: 'GET',
            success: function (data) {
                alert("The report has been updated.");
            },
            error: function (date) {
                alert("ERROR!");
            }
        })
    }

    function GenerateReport(LogType) {
        $.ajax({
            url: '/Crestwood/GenerateReport',
            data: { StartDate: document.getElementById('startdate').value, EndDate: document.getElementById('enddate').value, ReportType: LogType },
            type: 'GET',
            success: function (data) {
                alert("Report Generated Successfully!");
                window.open(data.file);
            },
            error: function (date) {
                alert("ERROR!");
            }
        })
    }*@

</script>