crm.chemtelinc.com/Models/MSDSSearch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace crm.chemtelinc.com.Models
{
    public class MSDSSearch
    {
        private string _id, _company, _productname, _language, _manufacturer, _productnumber, _date, _mis, _filename, _commonname;

        public string ID
        {
            get { return _id; }
            set { _id = value; }
        }
        public string Company
        {
            get { return _company; }
            set { _company = value; }
        }
        public string ProductName
        {
            get { return _productname; }
            set { _productname = value; }
        }
        public string Language
        {
            get { return _language; }
            set { _language = value; }
        }
        public string Manufacturer
        {
            get { return _manufacturer; }
            set { _manufacturer = value; }
        }
        public string ProductNumber
        {
            get { return _productnumber; }
            set { _productnumber = value; }
        }
        public string Date
        {
            get { return _date; }
            set { _date = value; }
        }
        public string MIS
        {
            get { return _mis; }
            set { _mis = value; }
        }
        public string FileName
        {
            get { return _filename; }
            set { _filename = value; }
        }
        public string CommonName
        {
            get { return _commonname; }
            set { _commonname = value; }
        }

        public MSDSSearch()
        {
            _company = "";
            _productname = "";
            _language = "";
            _manufacturer = "";
            _productnumber = "";
            _date = "";
            _mis = "";
            _filename = "";
            _commonname = "";
        }
    }
}

crm.chemtelinc.com/Controllers/MSDSSearchController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using crm.chemtelinc.com.Models;

namespace crm.chemtelinc.com.Controllers
{
    public class MSDSSearchController : Controller
    {
        string SqlSearchCriteria = "";
        // GET: MSDSSearch
        public ActionResult Index()
        {
            List<MSDSSearch> m = new List<MSDSSearch>();
            m = GetRecords();
            return View(m.ToList());
        }


        public List<MSDSSearch> GetRecords()
        {
            string Vdocconstring = Properties.Settings.Default.VdocConnectionString;
            string sql = "SELECT TOP 200 Company, ProductName, Language, Manufacturer, ProductNumber, Date, MIS, FileName, CommonName FROM msds ORDER BY Date";
            List<MSDSSearch> m = new List<MSDSSearch>();
            using (SqlConnection con = new SqlConnection(Vdocconstring))
            {
                using (SqlCommand cmd = new SqlCommand(sql, con))
                {
                    con.Open();
                    SqlDataReader sdr = cmd.ExecuteReader();
                    while (sdr.Read())
                    {
                        MSDSSearch ms = new MSDSSearch();
                        ms.Company = sdr["Company"].ToString();
                        ms.ProductName = sdr["ProductName"].ToString();
                        ms.Language = sdr["Language"].ToString();
                        ms.Manufacturer = sdr["Manufacturer"].ToString();
                        ms.ProductNumber = sdr["ProductNumber"].ToString();
                        ms.Date = sdr["Date"].ToString();
                        ms.MIS = sdr["MIS"].ToString();
                        ms.FileName = sdr["FileName"].ToString();
                        ms.CommonName = sdr["CommonName"].ToString();
                        m.Add(ms);
                    }
                }
            }
            return m;
        }

        public ActionResult SearchMSDS(FormCollection fc)
        {
            string SearchCriteria = fc["SearchBy"].ToString();
            string SearchTerm = fc["Search"].ToString();
            string AdvSearchCrit = "";
            string AdvSearchTerm = "";
            string AdvSortBy = "";
            string AdvSortOrder = "";

            if (fc["AdvSearchBy"] != null && fc["AdvSearchBy"].ToString() != "")
            {
                AdvSearchCrit = fc["AdvSearchBy"].ToString();
            }
            if (fc["AdvSearch"] != null && fc["AdvSearch"].ToString() != "")
            {
                AdvSearchTerm = fc["AdvSearch"].ToString();
            }
            if (fc["AdvSortBy"] != null && fc["AdvSortBy"].ToString() != "")
            {
                AdvSortBy = fc["AdvSortBy"].ToString();
            }
            if (fc["AdvSortOrder"] != null && fc["AdvSortOrder"].ToString() != "")
            {
                AdvSortOrder = fc["AdvSortOrder"].ToString();
            }


            string Vdocconstring = Properties.Settings.Default.VdocConnectionString;
            string sql = "SELECT ID, Company, ProductName, Language, Manufacturer, ProductNumber, Date, MIS, FileName, CommonName FROM msds ";
            //WHERE statements based on 
            if (SearchCriteria == "Product Name/Product Number")
            {
                sql += "WHERE (ProductName LIKE '%" + SearchTerm + "%' OR ProductNumber LIKE '%" + SearchTerm + "%')";
                if (AdvSearchTerm != null && AdvSearchTerm != "")
                {
                    sql += " AND [" + AdvSearchCrit + "] LIKE '%"+ AdvSearchTerm + "%'";
                }
            }
            if (SearchCriteria == "Company")
            {
                sql += "WHERE Company LIKE '%" + SearchTerm + "%'";
                if (AdvSearchTerm != null && AdvSearchTerm != "")
                {
                    sql += " AND [" + AdvSearchCrit + "] LIKE '%" + AdvSearchTerm + "%'";
                }
            }
            if (SearchCriteria == "Product Name")
            {
                sql += "WHERE ProductName LIKE '%" + SearchTerm + "%'";
                if (AdvSearchTerm != null && AdvSearchTerm != "")
                {
                    sql += " AND [" + AdvSearchCrit + "] LIKE '%" + AdvSearchTerm + "%'";
                }
            }
            if (SearchCriteria == "Language")
            {
                sql += "WHERE Language LIKE '%" + SearchTerm + "%'";
                if (AdvSearchTerm != null && AdvSearchTerm != "")
                {
                    sql += " AND [" + AdvSearchCrit + "] LIKE '%" + AdvSearchTerm + "%'";
                }
            }
            if (SearchCriteria == "Manufacturer")
            {
                sql += "WHERE Manufacturer LIKE '%" + SearchTerm + "%'";
                if (AdvSearchTerm != null && AdvSearchTerm != "")
                {
                    sql += " AND [" + AdvSearchCrit + "] LIKE '%" + AdvSearchTerm + "%'";
                }
            }
            if (SearchCriteria == "Product Number")
            {
                sql += "WHERE ProductNumber LIKE '%" + SearchTerm + "%'";
                if (AdvSearchTerm != null && AdvSearchTerm != "")
                {
                    sql += " AND [" + AdvSearchCrit + "] LIKE '%" + AdvSearchTerm + "%'";
                }
            }
            if (SearchCriteria == "Date")
            {
                sql += "Date LIKE '%" + SearchTerm + "%'";
                if (AdvSearchTerm != null && AdvSearchTerm != "")
                {
                    sql += " AND [" + AdvSearchCrit + "] LIKE '%" + AdvSearchTerm + "%'";
                }
            }

            //Add the ORDER BY based on user selection
            if (AdvSortBy != null && AdvSortBy != "")
            {
                sql += " ORDER BY [" + AdvSortBy + "]";
            }
            //Add the sort order ASC or DESC based on user selection
            if (AdvSortOrder != null && AdvSortOrder != "")
            {
                sql += " " + AdvSortOrder; 
            }

            ViewBag.SearchTerm = SearchTerm;
            ViewBag.AdvSearchTerm = AdvSearchTerm;

            List<MSDSSearch> m = new List<MSDSSearch>();
            using (SqlConnection con = new SqlConnection(Vdocconstring))
            {
                using (SqlCommand cmd = new SqlCommand(sql, con))
                {
                    con.Open();
                    SqlDataReader sdr = cmd.ExecuteReader();
                    while (sdr.Read())
                    {
                        MSDSSearch ms = new MSDSSearch();
                        ms.ID = sdr["ID"].ToString();
                        ms.Company = sdr["Company"].ToString();
                        ms.ProductName = sdr["ProductName"].ToString();
                        ms.Language = sdr["Language"].ToString();
                        ms.Manufacturer = sdr["Manufacturer"].ToString();
                        ms.ProductNumber = sdr["ProductNumber"].ToString();
                        ms.Date = sdr["Date"].ToString();
                        ms.MIS = sdr["MIS"].ToString();
                        ms.FileName = sdr["FileName"].ToString();
                        ms.CommonName = sdr["CommonName"].ToString();
                        m.Add(ms);
                    }
                }
            }
            return View("Index", m);
        }

        public ActionResult SortData(string SqlSearchCriteria)
        {
            ViewBag.SqlSearchCriteria = SqlSearchCriteria;
            string sql = SqlSearchCriteria + ", Date DESC";
            string Vdocconstring = Properties.Settings.Default.VdocConnectionString;

            List<MSDSSearch> m = new List<MSDSSearch>();
            using (SqlConnection con = new SqlConnection(Vdocconstring))
            {
                using (SqlCommand cmd = new SqlCommand(SqlSearchCriteria, con))
                {
                    con.Open();
                    SqlDataReader sdr = cmd.ExecuteReader();
                    while (sdr.Read())
                    {
                        MSDSSearch ms = new MSDSSearch();
                        ms.ID = sdr["ID"].ToString();
                        ms.Company = sdr["Company"].ToString();
                        ms.ProductName = sdr["ProductName"].ToString();
                        ms.Language = sdr["Language"].ToString();
                        ms.Manufacturer = sdr["Manufacturer"].ToString();
                        ms.ProductNumber = sdr["ProductNumber"].ToString();
                        ms.Date = sdr["Date"].ToString();
                        ms.MIS = sdr["MIS"].ToString();
                        ms.FileName = sdr["FileName"].ToString();
                        ms.CommonName = sdr["CommonName"].ToString();
                        m.Add(ms);
                    }
                }
            }
            return View("Index", m);
        }
    }
}

crm.chemtelinc.com/Views/MSDSSearch/Index.cshtml
@model IList<crm.chemtelinc.com.Models.MSDSSearch>
@{
    ViewBag.Title = "Index";
}

<h2>MSDS Search</h2>

<div class="GLOHeader" id="GRCPHeader">Control Panel</div>

<div style="text-align:center;">
    <br />
    @using (Html.BeginForm("SearchMSDS", "MSDSSearch", FormMethod.Post))
    {

        <div style="width:25%; display:inline-block;">
            <span>Search: </span>
            <input type="text" name="Search" id="Search" value="@ViewBag.SearchTerm"/>
        </div>

        <div style="width: 25%; display: inline-block;">
            <span>By: </span>
            <select name="SearchBy" id="SearchBy">
                <option value="Product Name/Product Number">Product Name/Product Number</option>
                <option value="Company">Company</option>
                <option value="Product Name">Product Name</option>
                <option value="Language">Language</option>
                <option value="Manufacturer">Manufacturer</option>
                <option value="Product Number">Product Number</option>
                <option value="Date">Date</option>
            </select>
        </div>

        <div style="text-align: left; width: 10%; display: inline-block;">
            <span>
                <a href="#" onclick="ToggleAdvSearch()">Advanced Search</a>
            </span>
        </div>

        <div style="width: 25%; display: inline-block;">
            <input type="submit" name="SearchBtn" id="SearchBtn" value="Search" />
            <input type="button" name="RefreshBtn" id="RefreshBtn" value="Refresh" onclick="RefreshPage()" />
            <input type="button" name="ViewMSDS" id="ViewMSDS" value="View MSDS" onclick="MSDSView()">
        </div>


        <div id="AdvSearchBlock">
            <hr />
            <div style="width:20%; display:inline-block;">
                <span>Search: </span>
                <input type="text" name="AdvSearch" id="Search" value="@ViewBag.AdvSearchTerm" />
            </div>

            <div style="width: 15%; display: inline-block;">
                <span>By: </span>
                <select name="AdvSearchBy" id="AdvSearchBy">
                    <option value=""></option>
                    <option value="Company">Company</option>
                    <option value="ProductName">Product Name</option>
                    <option value="Language">Language</option>
                    <option value="Manufacturer">Manufacturer</option>
                    <option value="ProductNumber">Product Number</option>
                    <option value="Date">Date</option>
                </select>
            </div>

            <div style="width:20%; display:inline-block;">
                <span>Order By: </span>
                <select name="AdvSortBy" id="AdvSortBy">
                    <option value=""></option>
                    <option value="Company">Company</option>
                    <option value="ProductName">Product Name</option>
                    <option value="Language">Language</option>
                    <option value="Manufacturer">Manufacturer</option>
                    <option value="ProductNumber">Product Number</option>
                </select>
            </div>

            <div style="width:20%; display:inline-block;">
                <span>Sort Order: </span>
                &nbsp;&nbsp;&nbsp;
                <input type="radio" name="AdvSortOrder" id="AdvSortOrder" value="ASC" />ASC
                <input type="radio" name="AdvSortOrder" id="AdvSortOrder" value="DESC" />DESC
            </div>
        </div>
    }
</div>
<br />
<div class="GLOHeader" id="GRCPHeader">MSDS Search Results - <b>@Model.Count() Records</b></div>
<table cellpadding="5" class="MSDSSearchTable">
    <tr>
        <th></th>
        <th>Company</th>
        <th>Product Name</th>
        <th>Language</th>
        <th>Manufacturer</th>
        <th>Product Number</th>
        <th>Date</th>
        <th>MIS</th>
        <th>File Name</th>
        <th>Common Name</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                <input type="radio" name="SelectedMSDS_@item.ID" value="@item.ID" onclick="FillMSDSInfo('@item.Company', '@item.MIS', '@item.FileName')" />
            </td>
            <td>@item.Company</td>
            <td>@item.ProductName</td>
            <td>@item.Language</td>
            <td>@item.Manufacturer</td>
            <td>@item.ProductNumber</td>
            <td>@item.Date</td>
            <td>@item.MIS</td>
            <td>@item.FileName</td>
            <td>@item.CommonName</td>
        </tr>
    }
</table>

<input type="hidden" name="SelectedCompany" id="SelectedCompany" />
<input type="hidden" name="SelectedMIS" id="SelectedMIS" />
<input type="hidden" name="SelectedFileName" id="SelectedFileName" />

<script>

    $(document).ready(function () {
        if ("@ViewBag.AdvSearchTerm" != "") {
            $("#AdvSearchBlock").show();
        } else {
            $("#AdvSearchBlock").hide();
        }
    });

    function RefreshPage() {
        location.href = "/MSDSSearch/Index";
    }

    function ToggleAdvSearch() {
        $("#AdvSearchBlock").slideToggle();
    }

    function FillMSDSInfo(Company, MIS, FileName) {
        document.getElementById("SelectedCompany").value = Company;
        document.getElementById("SelectedMIS").value = MIS;
        document.getElementById("SelectedFileName").value = FileName;
    }

    function MSDSView() {
        var Company = document.getElementById("SelectedCompany").value;
        var MIS = document.getElementById("SelectedMIS").value;
        var FileName = document.getElementById("SelectedFileName").value;
        window.open("https://crm.chemtel.net/MSDS/" + Company + "-" + MIS + "/" + FileName, '_blank');
    }
</script>