crm.chemtelinc.com/Controllers/TCEQController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using ChemicalLibrary;
using crm.chemtelinc.com.Models;
using CrystalDecisions.Shared;
using SendGrid;
using SendGrid.Helpers.Mail;

namespace crm.chemtelinc.com.Controllers
{
    public class TCEQController : Controller
    {
        public string constring = Properties.Settings.Default.chemicalConnectionString; //Class-level variable containg the connection string to the database.
        public string constringTest = Properties.Settings.Default.chemicalTestConnectionString; //Class-level variable containg the connection string to the database.
        string AttachedPath = "";
        public string IDRevise = "";
        bool submitted = false;
        bool updated = false;
        bool cancel = false;

        #region Load TCEQ Report
        public ActionResult TCEQReport()
        {
            //Check if user is logged in, if not, force login.
            if (Session["Username"] == null || Session["Username"].ToString() == "")
            {
                return RedirectToAction("Index", "Home", new { e = "You must login before proceeding!" });
            }
            //Get new Report ID
            int NewID = LastID();
            NewID = NewID + 1;
            ViewBag.NewID = NewID.ToString();

            //Get county list for dropdown
            List<string> Counties = new List<string>();
            Counties = CountyListNames();
            ViewBag.Counties = Counties;
            return View();
        }
        private int LastID()
        {
            int IDReport = 0;
            string strsql = "SELECT id FROM tceqreport ORDER BY id DESC";
            using (SqlConnection cn = new SqlConnection(constring))
            {
                cn.Open();
                using (SqlCommand cmd = new SqlCommand(strsql, cn))
                {
                    SqlDataReader rdr = cmd.ExecuteReader();
                    while (rdr.Read())
                    {
                        IDReport = int.Parse(rdr["id"].ToString());
                        break;
                    }
                }
            }
            return IDReport;
        }
        private List<string> CountyListNames()
        {
            List<string> C = new List<string>();
            string strsql = "SELECT countyName FROM glocountylist";
            using (SqlConnection cn = new SqlConnection(constring))
            {
                cn.Open();
                using (SqlCommand cmd = new SqlCommand(strsql, cn))
                {
                    SqlDataReader rdr = cmd.ExecuteReader();
                    while (rdr.Read())
                    {
                        C.Add(rdr[0].ToString());
                    }
                }
                if (C.Count == 0)
                {
                    C.Add("no county names found");
                }
            }
            return C;
        }
        #endregion
        #region Submit TCEQ Report
        public ActionResult SubmitTCEQReport(FormCollection fc)
        {
            TCEQ T = GetData(fc);
            if (fc["btnsubmit"].ToString() == "Update")
            {
                if (Update.UpdateTCEQ(constring, T))
                {
                    int ID = T.ID_TCEQ;
                    if (FillDataSet(ID))
                    {
                        submitted = true;
                    }
                }
            } else
            {
                if (Add.AddTCEQ(constring, T))
                {
                    int ID = this.LastID();
                    if (FillDataSet(ID))
                    {
                        submitted = true;
                    }
                }
            }
            TCEQEmailContact tef = new TCEQEmailContact();
            tef.ID = fc["TBIDReport"];
            tef.Reqion = fc["TBRegion"].ToString();
            tef.FilePath = AttachedPath;
            tef.FileViewPath = "https://crm.chemtel.net/Completed Reports/TCEQ/2023/TCEQ-" + fc["TBIDReport"].ToString() + ".pdf";
            tef.County = fc["CBCounty"].ToString();
            return View("TCEQEmailForm", tef);
        }
        private TCEQ GetData(FormCollection fc)
        {
            TCEQ t = new TCEQ();
            if (fc["TBIDReport"].ToString() != "")
            {
                t.ID_TCEQ = Int32.Parse(fc["TBIDReport"].ToString());
            }
            t.ERS_Operator = fc["TBERS"].ToString().ToUpper();
            t.Report_Date = fc["DTreportdate"].ToString();
            t.Report_Time = fc["TBRTime"].ToString();
            t.Incident_Date = fc["DTtincidentdate"].ToString();
            t.Incident_Time = fc["TBincidenttime"].ToString();
            t.Report_By = fc["TBreportedby"].ToString().ToUpper();
            t.Contact_Number = fc["TBContactNumber"].ToString();
            if (fc["TBContactNumber2"].ToString() == "")
            {
                t.Contact_Number_2 = "(000) 000-0000";
            } else
            {
                t.Contact_Number_2 = fc["TBContactNumber2"].ToString();
            }
            t.Emergency = fc["CBEmergency"].ToString();
            t.Description = fc["TBDescription"].ToString().ToUpper();
            t.Location = fc["TBLocation"].ToString().ToUpper();
            t.County = fc["CBCounty"].ToString();
            t.Material1 = fc["TBM1"].ToString().ToUpper();
            t.Material2 = fc["TBM2"].ToString().ToUpper();
            t.Material3 = fc["TBM3"].ToString().ToUpper();
            t.Material4 = fc["TBM4"].ToString().ToUpper();
            t.Material5 = fc["TBM5"].ToString().ToUpper();
            if (fc["TBCAS1"].ToString() == "") { t.CAS1 = "NA"; } else { t.CAS1 = fc["TBCAS1"].ToString(); }
            if (fc["TBCAS2"].ToString() == "") { t.CAS2 = "NA"; } else { t.CAS2 = fc["TBCAS2"].ToString(); }
            if (fc["TBCAS3"].ToString() == "") { t.CAS3 = "NA"; } else { t.CAS3 = fc["TBCAS3"].ToString(); }
            if (fc["TBCAS4"].ToString() == "") { t.CAS4 = "NA"; } else { t.CAS4 = fc["TBCAS4"].ToString(); }
            if (fc["TBCAS5"].ToString() == "") { t.CAS5 = "NA"; } else { t.CAS5 = fc["TBCAS5"].ToString(); }
            t.Amount1 = fc["TBAmount1"].ToString();
            t.Amount2 = fc["TBAmount2"].ToString();
            t.Amount3 = fc["TBAmount3"].ToString();
            t.Amount4 = fc["TBAmount4"].ToString();
            t.Amount5 = fc["TBAmount5"].ToString();
            t.Unit1 = fc["CBUnit1"].ToString();
            t.Unit2 = fc["CBUnit2"].ToString();
            t.Unit3 = fc["CBUnit3"].ToString();
            t.Unit4 = fc["CBUnit4"].ToString();
            t.Unit5 = fc["CBUnit5"].ToString();
            if (fc["CHAir"] != null && fc["CHAir"].ToString() == "Air")
            {
                t.Media_Affected = "Air";
            }
            if (fc["CHWater"] != null && fc["CHWater"].ToString() == "Water")
            {
                if (t.Media_Affected == "NA")
                {
                    t.Media_Affected = "Water";
                }
                else { t.Media_Affected = t.Media_Affected + ", Water"; }
            }
            if (fc["CHLand"] != null && fc["CHLand"].ToString() == "Land")
            {
                if (t.Media_Affected == "NA")
                {
                    t.Media_Affected = "Land";
                }
                else { t.Media_Affected = t.Media_Affected + ", Land"; }
            }
            if (fc["TBRW"].ToString() == "") { t.Receiving_Water = "N/A"; } else { t.Receiving_Water = fc["TBRW"].ToString().ToUpper(); }
            t.Amount_Water = fc["TBRWAmount"].ToString();
            t.Unit_Water = fc["CBRWUnit"].ToString();
            if (fc["TBPRCompany"].ToString() == "") { t.PR_Company = "UNKNOWN"; } else { t.PR_Company = fc["TBPRCompany"].ToString(); }
            if (fc["TBPRStreet"].ToString() == "") { t.PR_Street = "UNKNOWN"; } else { t.PR_Street = fc["TBPRStreet"].ToString(); }
            if (fc["TBPRCity"].ToString() == "") { t.PR_City = "UNKNOWN"; } else { t.PR_City = fc["TBPRCity"].ToString(); }
            if (fc["TBPRState"].ToString() == "") { t.PR_State = "NA"; } else { t.PR_State = fc["TBPRState"].ToString(); }
            if (fc["TBPRZipCode"].ToString() != "")
            {
                string Zip1 = fc["TBPRZipCode"].ToString().Substring(0, 5);
                string Zip2 = fc["TBPRZipCode"].ToString().Substring((fc["TBPRZipCode"].ToString().Length - 4), 4);
                t.PR_ZipCode = Zip1 + "-" + Zip2;
            } else
            {
                t.PR_ZipCode = "00000-0000";
            }
            if (fc["TBPRContact"].ToString() == "") { t.PR_Contact = "UNKNOWN"; } else { t.PR_Contact = fc["TBPRContact"].ToString(); }
            if (fc["TBPRPhone"].ToString() == "") { t.PR_Phone = "(000) 000-0000"; } else { t.PR_Phone = fc["TBPRPhone"].ToString(); }
            t.ResponderName = fc["TBRName"].ToString();
            t.NotificationTime = fc["TBNTime"].ToString();
            return t;
        }


        #endregion
        #region TCEQ Email Form
        public ActionResult TCEQEmailForm(TCEQEmailContact tef)
        {
            return View(tef);
        }

        public ActionResult CorrectTCEQReport(FormCollection fc)
        {
            ViewBag.Revised = "true";
            TCEQ t = new TCEQ(constring, int.Parse(fc["ReportID"].ToString()));  //Gets the desired report and puts it into a custom class variable.
            List<string> Counties = new List<string>(); //Get county list for dropdown
            Counties = CountyListNames();
            ViewBag.Counties = Counties;
            return View("TCEQReport", t);
        }

        public ActionResult SendTCEQEmail(FormCollection fc)
        {
            var client = new SendGridClient("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");

crm.chemtelinc.com/Views/TCEQ/TCEQEmailForm.cshtml
@model ChemicalLibrary.TCEQEmailContact

@{
    ViewBag.Title = "TCEQEmailForm";
}


<h2>TCEQ Email Form</h2>

<br />
<a href="javascript:void(0);" id="backLink" style="font-weight:bold;"> &#8592; Back to Report</a>
<br />
<br />
@using (Html.BeginForm("CorrectTCEQReport", "TCEQ", FormMethod.Post, new { @id = "TCEQCorrectForm" }))
{
    <input type="hidden" value="@Model.ID" name="ReportID" id="ReportID" />
    <input type="submit" value="<- Go Back" style="width:10%;" class="form-control" />
}

@using (Html.BeginForm("SendTCEQEmail", "TCEQ", FormMethod.Post, new { @id = "TCEQEmailForm" }))
{
    <div style="text-align:center;">
        <label name="tceqregionnumb" id="tceqregionnumb" style="font-weight:600;">TCEQ REGION NUMBER: @Model.Reqion</label>
        <br />
        <select id="AgentsList" size="10" onchange="AddNewEmail(this.value)" style="width:33%;">
            <option value="Spill01@tceq.texas.gov">Region 1 AMARILLO</option>
            <option value="Spill02@tceq.texas.gov">Region 2 LUBBOCK</option>
            <option value="Spill03@tceq.texas.gov">Region 3 ABILENE</option>
            <option value="Spill04@tceq.texas.gov">Region 4 DALLAS/ FT WORTH</option>
            <option value="Spill05@tceq.texas.gov">Region 5 TYLER</option>
            <option value="Spill06@tceq.texas.gov">Region 6 EL PASO</option>
            <option value="Spill07@tceq.texas.gov">Region 7 MIDLAND</option>
            <option value="Spill08@tceq.texas.gov">Region 8 SAN ANGELO</option>
            <option value="Spill09@tceq.texas.gov">Region 9 WACO</option>
            <option value="Spill10@tceq.texas.gov">Region 10 BEAUMONT</option>
            <option value="Spill11@tceq.texas.gov">Region 11 AUSTIN</option>
            <option value="Spill12@tceq.texas.gov">Region 12 HOUSTON</option>
            <option value="Spill13@tceq.texas.gov">Region 13 SAN ANTONIO</option>
            <option value="Spill14@tceq.texas.gov">Region 14 CORPUS CHRISTI</option>
            <option value="Spill15@tceq.texas.gov">Region 15 HARLINGEN</option>
            <option value="Spill16@tceq.texas.gov">Region 16 LAREDO</option>
        </select>
    </div>

    <div style="text-align:center;">
        <div>
            <span style="vertical-align:middle;display:inline">To</span> <textarea name="ToEmails" id="ToEmails" class="GLOFieldSpacing form-control" style="width: 80%; vertical-align: middle; display: inline;" required=""></textarea>
        </div>
        <br />
        <div>
            <span style="vertical-align:middle;display:inline">Subject</span> <input type="text" name="Subject" class="GLOFieldSpacing form-control" style="width: 80%; vertical-align: middle; display: inline;" value="TCEQ-@Model.ID" />
        </div>
        <br />
        <div>
            <span style="vertical-align:middle;display:inline">Attached</span> <input type="text" name="Attachment" class="GLOFieldSpacing form-control" style="width: 80%; vertical-align: middle; display: inline;" readonly="" value="@Model.FilePath" />
        </div>
        <br />
        <div>
            <span style="vertical-align:middle;display:inline">Message</span> <textarea name="Message" class="GLOFieldSpacing form-control" style="width: 80%; vertical-align: middle; display: inline;"></textarea>
        </div>
        <input type="submit" value="SEND" id="SendEmail" name="SendEmail" style="color:red;font-weight:600; width:25%;" class="GLOFieldSpacing form-control" />
    </div>
}

<script>    
    $(document).on('click', '#backLink', function () {
        history.go(-1);
    });
    @*$(document).ready(function () {
        window.open("@Model.FileViewPath");
    });*@
    function AddNewEmail(email) {
        document.getElementById("ToEmails").append(email + ", ");
    }
</script>

crm.chemtelinc.com/Views/TCEQ/TCEQReportLog.cshtml
@model IList<ChemicalLibrary.TceqLog>

@{
    ViewBag.Title = "TCEQReportLog";
}

<h2>TCEQ Report Log</h2>


<div id="generatereportcontainer" style="width: 50%; display: inline-block; text-align: center;">
    @using (Html.BeginForm("ReportSearch", "TCEQ", FormMethod.Post, new { id = "ReportSearchForm" }))
    {
        <span>Report Search</span>
        <hr />
        <input type="text" name="reportid" id="reportid" class="form-control GLOFieldSpacing" style="width:30%;" placeholder="TCEQ ID #" />
        <input type="hidden" name="submittype" id="submittype" />
        <input type="hidden" name="reportdate" id="reportdate" />
        <input type="button" value="Search" class="form-control GLOFieldSpacing" style="width:20%;" onclick="Search()" />
        <input type="button" value="View PDF" class="form-control GLOFieldSpacing" style="width: 20%;" onclick="ViewPDF()" />
        <input type="button" value="Revise" class="form-control GLOFieldSpacing" style="width: 20%;" onclick="Revise()" />
    }
</div>
<div id="reportsearchcontainer" style="width: 49%;display:inline-block;vertical-align:top; text-align:center;">
    @using (Html.BeginForm("LineReport", "TCEQ", FormMethod.Post))
    {
        <span>Monthly Report</span>
        <hr />
        <div style="display: inline-block; width: 50%;">
            <span>Start Date:</span>
            <input type="date" name="startdate" id="startdate" class="form-control GLOFieldSpacing" style="width:60%;" />
            <br />
            <span>End Date:</span>
            <input type="date" name="enddate" id="enddate" class="form-control GLOFieldSpacing" style="width:60%;" />
            <input type="submit" value="Generate Report" class="form-control GLOFieldSpacing" onclick="GenerateReport()" />
        </div>
    }
</div>
<hr />

<table cellpadding="5">
    <tr>
        <th></th>
        <th>ID</th>
        <th>ERS Operator</th>
        <th>Report Date</th>
        <th>Report Time</th>
        <th>Incident Date</th>
        <th>Incident Time</th>
        <th>Reported By</th>
        <th>Contact Number</th>
        <th>Other Contact Number</th>
        <th>County</th>
        <th>Notification Time</th>
    </tr>
    @foreach (var item in Model)
    {
        ;
        <tr id="Row_@item.ID">
            <td><input type="radio" name="IDSelected" value="@item.ID" onclick="FillTCEQID(this.value), FillReportDate(@item.ReportDate.Split('/')[2])" /></td> @* Have to split the date string and grab the year in order to send it to javascript *@ 
            <td>@item.ID</td>
            <td>@item.ERS</td>
            <td>@item.ReportDate</td>
            <td>@item.ReportTime</td>
            <td>@item.IncidentDate</td>
            <td>@item.IncidentTime</td>
            <td>@item.ReportedBy</td>
            <td>@item.ContactNumber</td>
            <td>@item.OtherNumbers</td>
            <td>@item.County</td>
            <td>@item.NotificationTime</td>
        </tr>
    }
</table>

<script>
    function GenerateReport() {
        var x = document.getElementById('startdate').value;
        var y = document.getElementById('enddate').value;
        return true;
    }
    function Search() {
        document.getElementById("submittype").value = "Search";
        document.getElementById("ReportSearchForm").submit();

    }
    function ViewPDF() {
        var id = document.getElementById("reportid").value;
        var year = document.getElementById("reportdate").value;
        window.open('https://crm.chemtel.net/Completed Reports/TCEQ/' + year + '/TCEQ-' + id + '.pdf', "_blank");
    }
    function Revise() {
        document.getElementById("submittype").value = "Revise";
        document.getElementById("ReportSearchForm").submit();
    }
    function FillTCEQID(id) {
        document.getElementById("reportid").value = id;
    }
    function FillReportDate(ReportYear) {
        document.getElementById("reportdate").value = ReportYear;
    }
</script>